package models

type Post struct {
	Id     int    `json:"id"`
	UserID int    `json:"user_id"`
	Title  string `json:"title"`
	Body   string `json:"body"`
}

type AutoGenerated struct {
	Meta  Meta    `json:"meta"`
	Posts []*Post `json:"data"`
}
type Links struct {
	Previous interface{} `json:"previous"`
	Current  string      `json:"current"`
	Next     string      `json:"next"`
}
type Pagination struct {
	Total int   `json:"total"`
	Pages int   `json:"pages"`
	Page  int   `json:"page"`
	Limit int   `json:"limit"`
	Links Links `json:"links"`
}
type Meta struct {
	Pagination Pagination `json:"pagination"`
}
