// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: parser.proto

package connection_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CreatorClient is the client API for Creator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreatorClient interface {
	Parse(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type creatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCreatorClient(cc grpc.ClientConnInterface) CreatorClient {
	return &creatorClient{cc}
}

func (c *creatorClient) Parse(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/parser.Creator/Parse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreatorServer is the server API for Creator service.
// All implementations must embed UnimplementedCreatorServer
// for forward compatibility
type CreatorServer interface {
	Parse(context.Context, *Request) (*Response, error)

}

// UnimplementedCreatorServer must be embedded to have forward compatible implementations.
type UnimplementedCreatorServer struct {
}

func (UnimplementedCreatorServer) Parse(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedCreatorServer) mustEmbedUnimplementedCreatorServer() {}

// UnsafeCreatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreatorServer will
// result in compilation errors.
type UnsafeCreatorServer interface {
	mustEmbedUnimplementedCreatorServer()
}

func RegisterCreatorServer(s grpc.ServiceRegistrar, srv CreatorServer) {
	s.RegisterService(&Creator_ServiceDesc, srv)
}

func _Creator_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreatorServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parser.Creator/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreatorServer).Parse(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Creator_ServiceDesc is the grpc.ServiceDesc for Creator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Creator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parser.Creator",
	HandlerType: (*CreatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _Creator_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parser.proto",
}
